FROM maven:3.9.6-eclipse-temurin-17 AS builder

WORKDIR /build
COPY . .
RUN mvn clean package

FROM eclipse-temurin:17-jre

WORKDIR /app
COPY --from=builder /build/target/maville-app-1.0-SNAPSHOT.jar /app/maville-app.jar
COPY --from=builder /build/target/lib/* /app/lib/

EXPOSE 7000

CMD ["java", "-cp", "maville-app.jar:lib/*", "api.MaVilleServer"]
